GCC: conflicting types for 'can_filter' params
Definition was previously updated to use uint32_t and int_t types for
the can_filter() function parameters but the declaration in the header
file didn't contain the same updates.  On GCC, this resulted in the
following error:

.../can_api.c:85:5: error: conflicting types for 'can_filter'
In file included from .../can_api.c:16:0:
.../can_api.h:68:15: note: previous declaration of 'can_filter' was here