drivers/usb: Add missing dependency on mbed-events
The compiler complained:

    In file included from .../mbed-os/drivers/usb/source/USBCDC_ECM.cpp:19:
    .../mbed-os/drivers/usb/include/usb/USBCDC_ECM.h:27:10: fatal error: events/EventQueue.h: No such file or directory
       27 | #include "events/EventQueue.h"
          |          ^~~~~~~~~~~~~~~~~~~~~