Align Mbed CLI 2 to Mbed CLI 1 on C/C++ language standard
Mbed CLI 2 doesn't specify C/C++ language standard "-std=gnu11" and "-std=gnu++14".
This commit align Mbed CLI 2 to Mbed CLI 1 on C/C++ language standard,
so that it can fix the error on Arm Compiler 6.21:
Error: ISO C++17 does not allow 'register' storage class specifier