Bugfix for IOTSFW-345: Adde missing check for optional auto_detect parameter in CLI options.
Test procedure:

* Check with mbed-ls installed:

$ singletest.py --auto -j 8
MBEDLS: Detecting connected mbed-enabled devices...
MBEDLS: Detected K64F, port: COM61, mounted: E:
Building library CMSIS (K64F, ARM)
Copy: startup_MK64F12.o
Copy: sys.o
Copy: cmsis_nvic.o
Copy: system_MK64F12.o

* Uninstall mbed-ls iools:

$ pip uninstall mbed-ls
Uninstalling mbed-ls:
  c:\python27\lib\site-packages\mbed_ls-0.1.4-py2.7.egg
  c:\python27\scripts\mbedls-script.py
  c:\python27\scripts\mbedls.exe
  c:\python27\scripts\mbedls.exe.manifest
Proceed (y/n)? y
  Successfully uninstalled mbed-ls

$ mbedls
'mbedls' is not recognized as an internal or external command,
operable program or batch file.

$ python
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mbed_lstools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mbed_lstools

* Check singletest.py work flow without mbed-ls:

$ singletest.py -i test_spec.json -M muts_all.json
Building library CMSIS (K64F, ARM)
Building library MBED (K64F, ARM)
Building project DETECT (K64F, ARM)
TargetTest::K64F::ARM::DTCT_1::Simple detect test [OK] in 0.50 of 10 sec
Building project DEV_NULL (K64F, ARM)
TargetTest::K64F::ARM::EXAMPLE_1::/dev/null [OK] in 3.49 of 20 sec
Building project HELLO (K64F, ARM)
TargetTest::K64F::ARM::MBED_10::Hello World [OK] in 0.38 of 5 sec
Building project TICKER (K64F, ARM)
TargetTest::K64F::ARM::MBED_11::Ticker Int [OK] in 11.35 of 15 sec