musca: Add detect_code for MUSCA B1
Wtihout the detect_code, `mbed-tools detect` will fail to detect any
connected ARM_MUSCA_B1 boards with the error:

    ERROR: Could not identify a board with the product code: '5007'.
    No connected Mbed devices found.

Add the detect_code for MUSCA B1 to targets.json so the board can be
reliably detected.

Fixes ARMmbed/mbed-tools#272